// <auto-generated />
using System;
using LibrarySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystem.Migrations
{
    [DbContext(typeof(LibrarySystemDbContext))]
    partial class LibrarySystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableBooks")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = new Guid("495fc7c7-557d-43af-82a2-8438d2c6f4e9"),
                            Author = "Alex Michaelides",
                            AvailableBooks = 10,
                            PageCount = 336,
                            Quantity = 10,
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            ID = new Guid("b899c390-6f62-42a3-b3f4-729005d8bf59"),
                            Author = "Tara Westover",
                            AvailableBooks = 8,
                            PageCount = 352,
                            Quantity = 8,
                            Title = "Educated"
                        },
                        new
                        {
                            ID = new Guid("8d306ef6-1376-4536-8676-1df4e0e0b41b"),
                            Author = "Michelle Obama",
                            AvailableBooks = 7,
                            PageCount = 448,
                            Quantity = 7,
                            Title = "Becoming"
                        },
                        new
                        {
                            ID = new Guid("4f801f25-99e0-4e3f-9237-5dba58cc1d46"),
                            Author = "Paulo Coelho",
                            AvailableBooks = 12,
                            PageCount = 208,
                            Quantity = 12,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            ID = new Guid("55796e04-24bf-4fd6-b32b-9a20d0f54ddd"),
                            Author = "George Orwell",
                            AvailableBooks = 9,
                            PageCount = 328,
                            Quantity = 9,
                            Title = "1984"
                        },
                        new
                        {
                            ID = new Guid("58653711-b6b7-4b1b-8c26-45523d12b24f"),
                            Author = "Yuval Noah Harari",
                            AvailableBooks = 11,
                            PageCount = 443,
                            Quantity = 11,
                            Title = "Sapiens"
                        },
                        new
                        {
                            ID = new Guid("916ad347-f822-4650-bbed-544dc1f5bff8"),
                            Author = "Harper Lee",
                            AvailableBooks = 5,
                            PageCount = 281,
                            Quantity = 5,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            ID = new Guid("0eff9311-d04e-4a6a-9b39-3130d6f0df0b"),
                            Author = "James Clear",
                            AvailableBooks = 14,
                            PageCount = 320,
                            Quantity = 14,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            ID = new Guid("ab4f3d51-e392-4a4b-a0eb-e6ea5e02b447"),
                            Author = "Charles Duhigg",
                            AvailableBooks = 13,
                            PageCount = 371,
                            Quantity = 13,
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            ID = new Guid("086c8b1f-04ef-4db5-9765-aa7b1fe3a4fa"),
                            Author = "J.R.R. Tolkien",
                            AvailableBooks = 6,
                            PageCount = 310,
                            Quantity = 6,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            ID = new Guid("a5659583-afcf-4d74-bb55-700aaebc5add"),
                            Author = "Frank Herbert",
                            AvailableBooks = 10,
                            PageCount = 688,
                            Quantity = 10,
                            Title = "Dune"
                        },
                        new
                        {
                            ID = new Guid("b320f6dc-dfd7-4d7d-aa1e-7227ef55c5bd"),
                            Author = "Jane Austen",
                            AvailableBooks = 8,
                            PageCount = 279,
                            Quantity = 8,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            ID = new Guid("06aeceb1-b588-4eb2-aed6-821402a1e850"),
                            Author = "J.D. Salinger",
                            AvailableBooks = 7,
                            PageCount = 277,
                            Quantity = 7,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            ID = new Guid("9ab6a213-ffa2-436f-9098-6c63a81a7f3d"),
                            Author = "Markus Zusak",
                            AvailableBooks = 9,
                            PageCount = 552,
                            Quantity = 9,
                            Title = "The Book Thief"
                        },
                        new
                        {
                            ID = new Guid("ef512f0e-4069-4b8a-a424-e3a4c99bf861"),
                            Author = "Aldous Huxley",
                            AvailableBooks = 5,
                            PageCount = 268,
                            Quantity = 5,
                            Title = "Brave New World"
                        },
                        new
                        {
                            ID = new Guid("09c65208-b180-4d78-9ec1-843a38e1fcc9"),
                            Author = "Cormac McCarthy",
                            AvailableBooks = 6,
                            PageCount = 287,
                            Quantity = 6,
                            Title = "The Road"
                        },
                        new
                        {
                            ID = new Guid("a647c522-3c84-47b0-b345-f235588d74ca"),
                            Author = "F. Scott Fitzgerald",
                            AvailableBooks = 10,
                            PageCount = 180,
                            Quantity = 10,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            ID = new Guid("3e4241c7-c1b7-4ac1-91e9-aab5b90f0690"),
                            Author = "Herman Melville",
                            AvailableBooks = 4,
                            PageCount = 635,
                            Quantity = 4,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            ID = new Guid("10860db3-9123-4e46-a6b4-5181b6aee70d"),
                            Author = "Fyodor Dostoevsky",
                            AvailableBooks = 7,
                            PageCount = 671,
                            Quantity = 7,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            ID = new Guid("273db004-798b-407e-b192-6509209b2b3a"),
                            Author = "Mary Shelley",
                            AvailableBooks = 8,
                            PageCount = 280,
                            Quantity = 8,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            ID = new Guid("11ab52c9-43d9-4f69-9f96-8e2b11890b8f"),
                            Author = "Charlotte Brontë",
                            AvailableBooks = 9,
                            PageCount = 532,
                            Quantity = 9,
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            ID = new Guid("bffd2e62-289c-429c-88e5-b2d296948db2"),
                            Author = "Bram Stoker",
                            AvailableBooks = 6,
                            PageCount = 418,
                            Quantity = 6,
                            Title = "Dracula"
                        },
                        new
                        {
                            ID = new Guid("0db925b6-9dc7-4b3b-865d-65b5f60675b3"),
                            Author = "Ray Bradbury",
                            AvailableBooks = 7,
                            PageCount = 194,
                            Quantity = 7,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            ID = new Guid("8fe01454-6ecb-43d6-a326-7ce7d74f2221"),
                            Author = "Stephen King",
                            AvailableBooks = 10,
                            PageCount = 447,
                            Quantity = 10,
                            Title = "The Shining"
                        },
                        new
                        {
                            ID = new Guid("c0e9c35c-b3fe-4eeb-8214-b0a3f59b6132"),
                            Author = "Andy Weir",
                            AvailableBooks = 11,
                            PageCount = 369,
                            Quantity = 11,
                            Title = "The Martian"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.BookRecord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BorrowedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BorrowedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.HasIndex("ProfileID");

                    b.ToTable("BookRecords");
                });

            modelBuilder.Entity("LibrarySystem.Models.Profile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ID = new Guid("686c2eea-a853-4e8d-b89f-24880d85c46f"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            RegistrationDate = new DateTime(2025, 5, 11, 20, 8, 6, 319, DateTimeKind.Utc).AddTicks(9794),
                            SecondName = "Doe",
                            isAdmin = false
                        },
                        new
                        {
                            ID = new Guid("9f947f58-69c2-4229-8227-c5296b5c8e4b"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            RegistrationDate = new DateTime(2025, 5, 11, 20, 8, 6, 319, DateTimeKind.Utc).AddTicks(9798),
                            SecondName = "Smith",
                            isAdmin = false
                        },
                        new
                        {
                            ID = new Guid("fd5b7bff-e07e-44bc-a43d-35598942d4f7"),
                            Email = "tom.jones@example.com",
                            FirstName = "Tom",
                            RegistrationDate = new DateTime(2025, 5, 11, 20, 8, 6, 319, DateTimeKind.Utc).AddTicks(9799),
                            SecondName = "Jones",
                            isAdmin = false
                        },
                        new
                        {
                            ID = new Guid("c6b47ac0-c5a1-44f6-9920-85cc435e1a75"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            RegistrationDate = new DateTime(2025, 5, 11, 20, 8, 6, 319, DateTimeKind.Utc).AddTicks(9801),
                            SecondName = "Johnson",
                            isAdmin = true
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.RemovedBook", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LostBook")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WornOutBook")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("RemovedBooks");
                });

            modelBuilder.Entity("LibrarySystem.Models.BookRecord", b =>
                {
                    b.HasOne("LibrarySystem.Models.Book", "Book")
                        .WithMany("BookRecords")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystem.Models.Profile", "Profile")
                        .WithMany("BookRecords")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LibrarySystem.Models.RemovedBook", b =>
                {
                    b.HasOne("LibrarySystem.Models.Book", "Book")
                        .WithOne("RemovedBooks")
                        .HasForeignKey("LibrarySystem.Models.RemovedBook", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.Navigation("BookRecords");

                    b.Navigation("RemovedBooks");
                });

            modelBuilder.Entity("LibrarySystem.Models.Profile", b =>
                {
                    b.Navigation("BookRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
